image: gradle:alpine

variables:
  GIT_STRATEGY: fetch

stages:
  - build

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  tags:
    - gradle